/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oryPencereler;

import dbcLib1.vtbaglatisi;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import oryLib1.oda;

/**
 *
 * @author Korcan
 */
public class OdaDuzenle extends javax.swing.JPanel {
    private int OdaNo;
    
    oda Oda=new oda();
    /**
     * Creates new form OdaDuzenle
     */
    public OdaDuzenle(int ID) throws SQLException {
        initComponents();
        OdaNo=ID;
        ResultSet sonuc=Oda.GetOdaElemanListe(ID);
        TipText.setText(sonuc.getString("tip"));
        KisiSayisiText.setText(sonuc.getString("kisiSayisi"));
        OtelNoText.setText(sonuc.getString("otelNo"));
        gu.setText(sonuc.getString("GunlukUcret"));
        durum.setText(sonuc.getString("durum"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KisiSayisiText = new javax.swing.JTextField();
        OtelNoText = new javax.swing.JTextField();
        TipText = new javax.swing.JTextField();
        TipLabel = new javax.swing.JLabel();
        KisiSayisiLabel = new javax.swing.JLabel();
        OtelNoLabel = new javax.swing.JLabel();
        DuzenleButon = new javax.swing.JButton();
        gu = new javax.swing.JTextField();
        OtelNoLabel1 = new javax.swing.JLabel();
        durum = new javax.swing.JTextField();
        OtelNoLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(163, 159));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        KisiSayisiText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KisiSayisiTextActionPerformed(evt);
            }
        });
        add(KisiSayisiText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 80, -1));
        add(OtelNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 80, -1));
        add(TipText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 80, -1));

        TipLabel.setText("Tip");
        add(TipLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        KisiSayisiLabel.setText("Kişi Sayısı");
        add(KisiSayisiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        OtelNoLabel.setText("OtelNo");
        add(OtelNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        DuzenleButon.setText("Duzenle");
        DuzenleButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DuzenleButonMouseClicked(evt);
            }
        });
        add(DuzenleButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 190, -1));
        add(gu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 80, -1));

        OtelNoLabel1.setText("Günlük Ücret ");
        add(OtelNoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 40));
        add(durum, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 80, -1));

        OtelNoLabel2.setText("Durum");
        add(OtelNoLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void DuzenleButonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DuzenleButonMouseClicked
        String tip=TipText.getText();
        int kisiSayisi=Integer.parseInt(KisiSayisiText.getText());
        int otelNo=Integer.parseInt(OtelNoText.getText());
        int durumg=Integer.parseInt(durum.getText());
        int gug=Integer.parseInt(gu.getText());
        try {
            Oda.OdaDuzenle(tip, kisiSayisi, otelNo, OdaNo,gug,durumg);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DuzenleButonMouseClicked

    private void KisiSayisiTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KisiSayisiTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KisiSayisiTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DuzenleButon;
    private javax.swing.JLabel KisiSayisiLabel;
    private javax.swing.JTextField KisiSayisiText;
    private javax.swing.JLabel OtelNoLabel;
    private javax.swing.JLabel OtelNoLabel1;
    private javax.swing.JLabel OtelNoLabel2;
    private javax.swing.JTextField OtelNoText;
    private javax.swing.JLabel TipLabel;
    private javax.swing.JTextField TipText;
    private javax.swing.JTextField durum;
    private javax.swing.JTextField gu;
    // End of variables declaration//GEN-END:variables
}
