/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oryPencereler;

import com.mysql.jdbc.Statement;
import dbcLib1.vtbaglatisi;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import oryLib1.oda;

/**
 *
 * @author Korcan
 */
public class OdaEkle extends javax.swing.JPanel {
    oda Oda=new oda();
    /**
     * Creates new form OdaEkle
     */
    public OdaEkle() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KisiSayisiText = new javax.swing.JTextField();
        OtelNoText = new javax.swing.JTextField();
        TipText = new javax.swing.JTextField();
        TipLabel = new javax.swing.JLabel();
        KisiSayisiLabel = new javax.swing.JLabel();
        OtelNoLabel = new javax.swing.JLabel();
        EkleButon = new javax.swing.JButton();
        durum = new javax.swing.JTextField();
        gu = new javax.swing.JTextField();
        OtelNoLabel1 = new javax.swing.JLabel();
        OtelNoLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(KisiSayisiText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 80, -1));
        add(OtelNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, -1));
        add(TipText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 80, -1));

        TipLabel.setText("Tip");
        add(TipLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 14, -1, -1));

        KisiSayisiLabel.setText("Kişi Sayısı");
        add(KisiSayisiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        OtelNoLabel.setText("OtelNo");
        add(OtelNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        EkleButon.setText("Ekle");
        EkleButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EkleButonMouseClicked(evt);
            }
        });
        add(EkleButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 160, -1));
        add(durum, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 80, -1));
        add(gu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 80, -1));

        OtelNoLabel1.setText("Günlük Ücret ");
        add(OtelNoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 40));

        OtelNoLabel2.setText("Durum");
        add(OtelNoLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void EkleButonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EkleButonMouseClicked
        String tip=TipText.getText();
        int kisiSayisi=Integer.parseInt(KisiSayisiText.getText());
        int otelNo=Integer.parseInt(OtelNoText.getText());
        int durumg=Integer.parseInt(durum.getText());
        int gug=Integer.parseInt(gu.getText());
        try {
            Oda.OdaEkle(tip, kisiSayisi, otelNo,gug,durumg);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_EkleButonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EkleButon;
    private javax.swing.JLabel KisiSayisiLabel;
    private javax.swing.JTextField KisiSayisiText;
    private javax.swing.JLabel OtelNoLabel;
    private javax.swing.JLabel OtelNoLabel1;
    private javax.swing.JLabel OtelNoLabel2;
    private javax.swing.JTextField OtelNoText;
    private javax.swing.JLabel TipLabel;
    private javax.swing.JTextField TipText;
    private javax.swing.JTextField durum;
    private javax.swing.JTextField gu;
    // End of variables declaration//GEN-END:variables
}
