/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oryPencereler;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import oryLib1.otel;
import oryLib1.rezervasyon;

/**
 *
 * @author mehmet
 */
public class rezervasyonPencere extends javax.swing.JPanel implements pencereKok{
int otelno=otel.getSecilenOtel();
    
    rezervasyon rezervasyon = new rezervasyon(otelno);
    /**
     * Creates new form rezervasyonPencere
     */
    public rezervasyonPencere() {
        try {
            initComponents();
            DefaultTableModel tablo = (DefaultTableModel) jTable1.getModel();
            tablo.setRowCount(0);
            ResultSet data=rezervasyon.GetRezevasyonElemanListe();
            while (data.next()) {
                tablo.addRow(new Object[]{data.getObject("rezervasyonNo"), data.getObject("odaNo"), data.getObject("musteriNo"), data.getObject("girisTarihi"), data.getObject("cikisTarihi"), data.getObject("otelNo")});
            }
        } catch (SQLException ex) {
            Logger.getLogger(otelPencere.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "rezervasyonNo", "odaNo", "musteriNo", "girisTarihi", "cikisTarihi", "otelNo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
